# Generated by Django 3.0.5 on 2020-12-01 08:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('visited', models.BooleanField(blank=True)),
                ('scrapy', models.BooleanField(blank=True)),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_crawled', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('click_ratio', models.IntegerField(blank=True)),
                ('location', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Website')),
            ],
        ),
    ]
