# Generated by Django 3.0.5 on 2020-12-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_webpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='owner',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
