# Generated by Django 3.0.5 on 2020-12-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20201201_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backward_Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
                ('urls', models.TextField()),
            ],
        ),
    ]
